[project]
name = "pth-tutorial"
version = "0.1.0"
description = "torch.compile tutorial"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.3",
    "tabulate>=0.9.0",
    "transformers[torch]>=4.53.2",
]
